dbt_proj:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      project: "{{ env_var('GOOGLE_CLOUD_PROJECT') }}"
      dataset: DBT_DEV
      threads: 32
      timeout_seconds: 300
      priority: interactive

    prod:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      project: "{{ env_var('GOOGLE_CLOUD_PROJECT') }}"
      dataset: DBT_PROD
      threads: 32
      timeout_seconds: 300
      priority: interactive