name: scheduled_run

on:
  schedule:
    - cron:  '0 12 * * *'
  push:
      branches:
        - main
env:
  DBT_PROFILES_DIR: ./
  GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}

jobs:
  scheduled_run:
    name: scheduled_run
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.DBT_GOOGLE_BIGQUERY_KEYFILE }}'

      - name: Install dependencies
        run: |
          pip install dbt-bigquery
          dbt deps --project-dir dbt_proj --target prod

      - name: Run dbt models
        run: dbt run --project-dir dbt_proj --target prod

      - name: Test dbt models
        run: dbt test --project-dir dbt_proj --target prod